#!/bin/bash

print_usage(){
cat << EOF
Usage:
$0 <project_name> <template_name>

Will copy template from <template_name> to <project_name>
EOF
}

if [ -z "$1" ]
then
        echo "No project name given"
        exit 1
fi


project_name=$1

template_dir="$HOME/.tools/go_project_templates"
template=default

if [ -n "$2" ]
then
	template="$2"
fi


if [ -e $project_name ]
then
	echo "Making backup of exisiting $project_name"
	mv "$project_name" "${project_name}.bak"
fi

cp -R "$template_dir/$template" $project_name

find ${project_name} -type f|xargs -I {FILES} sed -i "s/{{project_name}}/${project_name}/g" {FILES}
