#!/bin/bash

print_usage(){
cat << EOF
Usage:
$0 <project_name> <template_name>

Will copy template from <template_name> to <project_name>
EOF
}

if [ -z "$1" ]
then
        echo "No project name given"
	print_usage
        exit 1
fi

project_name=$1

template_dir="go_project_templates"
template=default

if [ -n "$2" ]
then
	template="$2"
fi

boil_project "$project_name" "${template_dir}/$template"
