#!/bin/bash

print_usage(){
cat << EOF
Usage:
$0 <project_name> 

Will copy dsl template to <project_name>
EOF
}

if [ -z "$1" ]
then
        echo "No project name given"
	print_usage
        exit 1
fi

boil_go "$1" dsl
