#!/bin/sh
find=$1
shift
replace=$1
shift
scope=$@

print_usage () {
echo "Usage:
refactorName FIND REPLACE SCOPE"
}


if [ -z $3 ]
then
print_usage
else
	echo "Refactoring $find to $replace in $scope"
	grep $find $scope -ls|xargs -I {} sed -ibak -e "s/$find/$replace/g" {}
fi

