#!/bin/bash

print_usage(){
printf "$0 [-n windows] [-s] dir

-n num_windows	how many windows to show (default 1)
-a 		autoplayed slideshow, delay of 2 seconds
-s delay	slideshow with delay of <delay> seconds

Shows images on n screens from dir"
}

n_screens=1
delay=2

while getopts n:s:a o
do
	case "$o" in
	 n)
		 echo "$OPTARG screens"
		if [ $OPTARG ]
		then
	 		n_flag=true
	 		n_screens="$OPTARG"
		else
			print_usage
			exit 1
		fi
		;;
	 a)
		slideshow=true
		;;
	 s)
	 	slideshow=true
		delay=$OPTARG
		;;
	 *)
	 	print_usage
                exit 1
		;;
	esac
done

dir=${@: -1}

echo "Showing images on $n_screens screens"

for (( i = 0; i < $n_screens; i++ ))
do
	echo "starting window $i"
	if [ $slideshow ]
	then
		feh $dir/*{jpg,jpeg,png,bmp,gif} $dir/**/*{jpg,jpeg,png,bmp,gif} -. -z -D $delay &>/dev/null & 
	else
		feh $dir/*{jpg,jpeg,png,bmp,gif} $dir/**/*{jpg,jpeg,png,bmp,gif} -. -z &>/dev/null &
	fi
	disown
done
