#!/bin/bash

if [ -z "$1" ];
then
	echo "No filename given"
	exit 1
fi

report_name=$1

tex_file=${report_name}.tex
pdf_file=${report_name}.pdf

i3-sensible-terminal -e "nvim -u ~/.vimrc ${tex_file}" &> /dev/null &
disown

i3-sensible-terminal -e "ls ${tex_file} | entr -src 'make' " &> /dev/null &
disown

xreader ${pdf_file} &> /dev/null & 
disown
